import pg from "pg";
import { config } from "../../config.js";

/**
 * A single connection pool for the process.
 *
 * pg returns bigint columns as strings by default, because a PostgreSQL bigint does not
 * fit in a JavaScript number. Every id in this schema is generated by an identity
 * column starting at 1, so the values stay far below Number.MAX_SAFE_INTEGER and
 * parsing them into numbers is safe and keeps the rest of the code free of string ids.
 */
pg.types.setTypeParser(pg.types.builtins.INT8, (value) => Number.parseInt(value, 10));

export const pool = new pg.Pool({
  connectionString: config.database.url,
  max: config.database.poolSize,
  // A connection that cannot be established should fail the request quickly rather than
  // hold it open until the client gives up.
  connectionTimeoutMillis: 5_000,
  idleTimeoutMillis: 30_000,
});

export type DbClient = pg.PoolClient;

export const closePool = () => pool.end();
